package com.github.duankang.service.entities;

import java.io.Serializable;
import java.util.Date;

public class Task implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskls.taskid
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskls.taskname
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskls.begintime
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskls.endtime
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskls.progress
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    private String progress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskls.taskInterval
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    private String taskinterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskls.taskCount
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    private String taskcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskls.taskid
     *
     * @return the value of taskls.taskid
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskls.taskid
     *
     * @param taskid the value for taskls.taskid
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskls.taskname
     *
     * @return the value of taskls.taskname
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskls.taskname
     *
     * @param taskname the value for taskls.taskname
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname == null ? null : taskname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskls.begintime
     *
     * @return the value of taskls.begintime
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskls.begintime
     *
     * @param begintime the value for taskls.begintime
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskls.endtime
     *
     * @return the value of taskls.endtime
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskls.endtime
     *
     * @param endtime the value for taskls.endtime
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskls.progress
     *
     * @return the value of taskls.progress
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public String getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskls.progress
     *
     * @param progress the value for taskls.progress
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public void setProgress(String progress) {
        this.progress = progress == null ? null : progress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskls.taskInterval
     *
     * @return the value of taskls.taskInterval
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public String getTaskinterval() {
        return taskinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskls.taskInterval
     *
     * @param taskinterval the value for taskls.taskInterval
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public void setTaskinterval(String taskinterval) {
        this.taskinterval = taskinterval == null ? null : taskinterval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskls.taskCount
     *
     * @return the value of taskls.taskCount
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public String getTaskcount() {
        return taskcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskls.taskCount
     *
     * @param taskcount the value for taskls.taskCount
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    public void setTaskcount(String taskcount) {
        this.taskcount = taskcount == null ? null : taskcount.trim();
    }
}