package com.github.duankang.service.dao;

import com.github.duankang.service.entities.Task;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskls
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskls
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskls
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskls
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    Task selectByPrimaryKey(String taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskls
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taskls
     *
     * @mbggenerated Sun Sep 08 09:30:33 GMT+08:00 2019
     */
    int updateByPrimaryKey(Task record);
}